### ISSUE TITLE
Press event on scrollabars

### ISSUE THREAD

**Issue by kreig** [ngryman/jquery.finger#42]
I have a problem with the `press` event in desktop browsers. When I scroll the div with `overflow:auto` using scrollbar (not a mouse wheel) `press` event is fired despite the cursor was actually moved.

Here is the [example](http://codepen.io/anon/pen/aOxZqG).

Environment: Chrome 44.0.2403.130 m, Windows 8.1.

**Comment by ngryman** [comment]
Hi, sorry for the late.

Nice catch! I won't fix this as it's really an edge case and can easily be fixed by ignoring the scrollbar in your css selector, something like this works in Chrome `$('body:not(::-webkit-scrollbar)')on('...')`. For other browsers you can [read this](https://css-tricks.com/almanac/properties/s/scrollbar/).

If you want to generalize this to your whole application with something a little less verbose, you can create a [custom selector](http://www.sitepoint.com/make-your-own-custom-jquery-selector/).
This would allow you to do something like this: `$('body:no-scrollbars)')on('...')`, assuming you created a `no-scrollbar` custom selector.
