### ISSUE TITLE
Prevent default `tap` not working in Firefox with touch

### ISSUE THREAD

**Issue by jacobbuck** [ngryman/jquery.finger#44]
The behaviour happening on Android, or when "Simulate touch events" is enabled.

Demo: http://jsfiddle.net/ys10otwe/

**Comment by jacobbuck** [comment]
By the way, I'm testing this on Firefox 41.0.1 on a Mac. Haven't checked Windows or Linux yet.

Another demo: http://jsfiddle.net/epn79zc7/2/

Chrome shows "tap" then "click", Firefox only shows "click" :confused:

**Comment by ngryman** [comment]
Basically **fingers** prevents `tap` events in the native `touchend` event, which should avoid synthesizing a `click` event.
It seems that Firefox is not behaving that way, not complying with other browsers behavior.
I won't be able to fix this because the current implementation of **finger** does not allow me to prevent any behavior in the `touchstart` event using `e.preventDefault()`.

But, there is a workaround, you could use the global `preventDefault` option which prevents default behavior in the `touchstart` native event:
```javascript
$.Finger.preventDefault = true;
$('a').on('tap', function() {
  console.log("every finger's event prevents default behavior");
});
```

refs:
 - https://bugzilla.mozilla.org/show_bug.cgi?id=861876
 - https://bugzilla.mozilla.org/show_bug.cgi?id=653009
