### ISSUE TITLE
mouse press, flick?

### ISSUE THREAD

**Issue by Zibri** [ngryman/jquery.finger#59]
In my app (which works on mobile AND pc) I wish to setup up 4 actions for an element:

tap, doubletab and press and flick.

if I use jquery finger, it works perfectly on mobile but on pc everything is ignored.

is there a way to UNIFY the events no matter if they happen with a finger on a mobile or with a mouse on a pc?

**Comment by ngryman** [comment]
Hey @Zibri, I think since jQuery Finger was created desktop browsers have changed the way they treat touch events. At this point, you probably want to use something more reliable that is still maintained. I would advise you to use something like [Hammer.js](https://hammerjs.github.io/getting-started/).
